### ISSUE TITLE
Communications Tower

### ISSUE THREAD

**Issue by firejake308** [firejake308/code-versus-bugs#14]
In order to educate the user about networking structure and devices, it is necessary for us to implement a Communications Tower. The communications tower should have multiple modes to illustrate the different network topologies. According to my research, the following topologies are reasonable in our scenario:
* star
>All towers in range of communications tower connect to the tower. Packets start at an attack tower, move to the hub, or the communication tower, and the hub then sends the packets to another tower.
* mesh
>All towers in range of communications tower connect to one other tower in the range of the communication tower. Packets are passed from one tower to the next randomly or using a* pathfinding and never actually rated the comm tower.
* bus
>There are 2 communications towers, and there is a connection between them. All towers within range of the connection connect directly to that line instead of to a comm tower. Packets originate from an attack tower, head to the main connection, aka the bus, and then bounce back and forth on the bus until they reach the intended target.

For more information, this website has a pretty good explanation of networks topologies. http://www.tutorialspoint.com/data_communication_computer_network/computer_network_topologies.htm

This task can be divided into the following subtasks:
- [x] Create an image for the comm tower
- [x] Create a class for the comm tower
- [x] Create a class for packets that travel between towers and hold information about malware
- [x] Implement the packets in a meaningful way
- [x] Add tutorial slides for the comm tower
- [x] Allow files to move toward towers #37

**Comment by patrickkenney9801** [comment]
Done!
