### ISSUE TITLE
Track/upgrade panel overlap

### ISSUE THREAD

**Issue by firejake308** [firejake308/code-versus-bugs#26]
When a second tower is selected while the upgrade panel is already up, the upgrade panel will appear on top. This is probably an error in GamePanel. This should be easily fixed by raising the layer of the upgrades panel.

**Comment by firejake308** [comment]
I don't have this in my copy, please paste in the fix when you get a chance.

**Comment by patrickkenney9801** [comment]
Oh yea...haha...uh funny story that one...uh... you know how um...certain
"fixes"...kind of..you know...uh...completely ruin the game?...well
uh...that one did uh...that

**Comment by firejake308** [comment]
Fixed by Patrick
