### ISSUE TITLE
Buttons Visual Update

### ISSUE THREAD

**Issue by firejake308** [firejake308/code-versus-bugs#35]
Java's default buttons are ugly. We need better ones.

**Comment by firejake308** [comment]
@patrickkenney9801 You're in IED, so what do you think about drawing circuit diagrams for the letters? For example the G in game could have a battery on the right and loop around to form a short circuit, and the letter N could have a switch or something.

**Comment by patrickkenney9801** [comment]
Uhh......

**Comment by firejake308** [comment]
The alternative is to use a digital display. Is that better?

**Comment by patrickkenney9801** [comment]
No sé que eso es.

**Comment by firejake308** [comment]
Like one on a digital clock.
https://www.google.com/search?q=digital+display&espv=2&biw=1366&bih=643&tbm=isch&imgil=QPJUn6Eagzw3SM%253A%253B7ACLyTVPXEkPzM%253Bhttp%25253A%25252F%25252Fjyled.manufacturer.globalsources.com%25252Fsi%25252F6008832101383%25252Fpdtl%25252FFour-digit-7%25252F1053118382%25252FFour-digital-Display-Screen.htm&source=iu&pf=m&fir=QPJUn6Eagzw3SM%253A%252C7ACLyTVPXEkPzM%252C_&usg=__u6aBdzFNs7u2TcHr2LcssiX8Afo%3D

**Comment by patrickkenney9801** [comment]
Sí, vamos eso.

**Comment by firejake308** [comment]
By the way, you don't have to do `\n`s in upgrade info anymore because I made the info box scroll and word wrap. I'm fixing that on your comm tower stuff from yesterday. I also thickened the lines on communications tower image.

**Comment by patrickkenney9801** [comment]
Gracias, necesito eso.

**Comment by patrickkenney9801** [comment]
Necesité*

**Comment by firejake308** [comment]
Estás practicando el español, yo veo. Escuché que voy a haber una prueba esta semana.

**Comment by firejake308** [comment]
Pienso que estás en un carro y no puedes usar una computadora?

**Comment by patrickkenney9801** [comment]
Sí, eres verdad.

**Comment by firejake308** [comment]
¡Que asco!, porque estoy en línea ahora.

**Comment by patrickkenney9801** [comment]
¿Qué es asco?

**Comment by firejake308** [comment]
Que asco = Bad luck, I think. Btw, new communications tower looks horrible after scaling. I'll need to fix it again...

**Comment by patrickkenney9801** [comment]
That is...unfortunate

**Comment by firejake308** [comment]
Do you think we could set default screen size to 1024 x 780?

**Comment by firejake308** [comment]
Right now, default width is like 1322

**Comment by patrickkenney9801** [comment]
Default?

**Comment by firejake308** [comment]
actually, it's closer to 1432

**Comment by patrickkenney9801** [comment]
I believe we need one more, extremely OP tower, then we're done

**Comment by firejake308** [comment]
Sure, no problem. Just make cost like infinite. Make an issue for it if you want, or add it to to-do list on Keep. Besides, I did want another tower that used projectiles.

**Comment by patrickkenney9801** [comment]
Good, it should be like super monkey, like a programmer perhaps?

**Comment by firejake308** [comment]
UPDATE: Back button on start menu is the only button left to fix.

**Comment by firejake308** [comment]
Done!
