### ISSUE TITLE
Check Placement

### ISSUE THREAD

**Issue by firejake308** [firejake308/code-versus-bugs#38]
Attempting to place a tower directly below another tower results in an "Invalid location", even though it is clearly not.

**Comment by firejake308** [comment]
Solved. The error was caused by a typo on line 272 of ShopPanel, where ```Rectangle curr = new Rectangle(Tower.allTowers[t].getX(), Tower.allTowers[t].getY(), 
						Tower.sprites[t].getWidth(), Tower.sprites[t].**getY()**;``` was written when it should've been ```Rectangle curr = new Rectangle(Tower.allTowers[t].getX(), Tower.allTowers[t].getY(), 
						Tower.sprites[t].getWidth(), Tower.sprites[t].**getHeight()**);```

**Comment by patrickkenney9801** [comment]
You fixed this?

**Comment by firejake308** [comment]
I fixed it, since it was after all my own mistake, but I hadn't committed
it, so I was waiting to close the issue.
