### ISSUE TITLE
Finish Story Mode

### ISSUE THREAD

**Issue by firejake308** [firejake308/code-versus-bugs#39]
We need to finish all 50 levels of story mode. Currently, we have up to level 24, where the last 5 levels are introducing the late-game malware types. I think the last 26 levels can just mix together different malware types in different, increasingly ways. Although I'd rather not change the levels that we've already written, if we want to phase in the late-game malwares slowly rather than just introducing them all at once, we can, but some of the tutorial levels will have to be rewritten.

**Comment by patrickkenney9801** [comment]
I want those other 4 types of minions!

**Comment by firejake308** [comment]
Huh? I already gave you viruses, spyware, bots, and trojans? What else is there?

**Comment by patrickkenney9801** [comment]
the other 4 mutations of minions I've been talking about forever

**Comment by firejake308** [comment]
What do they specialize in?

**Comment by patrickkenney9801** [comment]
well just make 2 smaller minions than the small one, and 2 bigger minions
than the  big one, i'll handle stats

**Comment by firejake308** [comment]
For example, we have high-health and high-speed varieties. What else
matters? By the way, I'm not at my computer right now.

**Comment by patrickkenney9801** [comment]
nothing tbh, anyways these are just to fill in the gaps so we can buff the
other malwares, they aren't supposed to be special, like different balloons
on btd

**Comment by firejake308** [comment]
I think we could do 50 levels without new minions, using just the malwares
we already have; rather, minions might just scale stats into the late game
(though not significantly). I honestly wasn't really expecting too many
minions in the end-game to begin with, much less respectable minions.

Anyway, if you absolutely insist on more minions, what color and size, in
pixels (estimate is fine) do you want them?

**Comment by patrickkenney9801** [comment]
Idk, up to you but you know my specifications, perhaps make some bigger or
smaller if you cant scale it correctly?

**Comment by firejake308** [comment]
Done with v0.6.2
