### ISSUE TITLE
Life lost tutorial doesn't resume to proper slide

### ISSUE THREAD

**Issue by firejake308** [firejake308/code-versus-bugs#42]

**Comment by firejake308** [comment]
Should be fixed v0.3.7

**Comment by firejake308** [comment]
Nope, it still isn't fixed.

**Comment by jasonpelham45** [comment]
I think this may have been what caused the infinite money glitch

**Comment by firejake308** [comment]
Killing tutorial, also killing this bug.

**Comment by jasonpelham45** [comment]
Wait you're killing off the whole tutorial?

**Comment by firejake308** [comment]
Yeah, we're replacing it with a help dialog that you can access at any time.

**Comment by jasonpelham45** [comment]
Ok that sounds more reasonable and less likely to mess up
