### ISSUE TITLE
Disc throwers OP

### ISSUE THREAD

**Issue by firejake308** [firejake308/code-versus-bugs#46]
Disc throwers appear to be OP. I made it to round 16 with only a single fully upgraded disc thrower without losing any lives. To be fair, I also bought a scanner and a firewall, but I deleted those before they got any kills. I spent all of my hardware points in damage, and I had approximately $3000 when time constraints forced me to save and close. I will continue the game when I get a chance and let you know how I do with viruses or spyware.

**Comment by patrickkenney9801** [comment]
Nerf attempt #1
