### ISSUE TITLE
Infinite Money

### ISSUE THREAD

**Issue by patrickkenney9801** [firejake308/code-versus-bugs#47]
Tutorial loop gives 200$ forever

**Comment by firejake308** [comment]
What round and tutorial slide?

**Comment by patrickkenney9801** [comment]
Idk but the one where you have to buy a firewall

**Comment by firejake308** [comment]
So, it added 200 on every tutorial slide after that, or ... ?

**Comment by patrickkenney9801** [comment]
No it looped

**Comment by firejake308** [comment]
Worry not- the tutorial itself will be abolished! The problem will be eliminated at its roots!
