### ISSUE TITLE
New and  Improved Tutorial

### ISSUE THREAD

**Issue by firejake308** [firejake308/code-versus-bugs#50]
It appears that the majority of the tutorial needs to be rewritten, and that my original way of doing the tutorial is not rewrite-friendly. I task you with making a better tutorial, and I authorize you to scrap my currentbone entirely if youxdeem it necessary.

**Comment by firejake308** [comment]
It has been decided that the tutorial will be abolished and replaced by a help dialog. Work on this dialog is under way at this moment.

**Comment by firejake308** [comment]
Don't forget to add stuff about the modem in the help menu. While you're at it, you might as well explain all the upgrades in the hardware panel.

**Comment by patrickkenney9801** [comment]
Get on

**Comment by firejake308** [comment]
Well, it appears the tables have turned: I have to study for Spanish.

**Comment by patrickkenney9801** [comment]
-.-

**Comment by patrickkenney9801** [comment]
What about the exe?

On Thu, Jan 15, 2015 at 8:14 PM, Patrick Kenney <patrickkenney9801@gmail.com

**Comment by firejake308** [comment]
Tell me when you're done, an  I'll make it.

**Comment by patrickkenney9801** [comment]
Finished
