### ISSUE TITLE
Game Won

### ISSUE THREAD

**Issue by firejake308** [firejake308/code-versus-bugs#52]
There needs to be a way to win the game. The game should show a dialog saying something like, "You defeated the hackers! Hooray!" We may or may not add an option to continue in freeplay or quit the game.

**Comment by firejake308** [comment]
Oh, dang it! I left this out of v0.7.1! @patrickkenney9801, don't you dare forget this in v1.0.0.

**Comment by patrickkenney9801** [comment]
Done
