### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by patrickkenney9801** [firejake308/code-versus-bugs#58]
We need a good presentation-one prepared in order to get those points

**Comment by firejake308** [comment]
To begin with, should we use Prezi or PowerPoint?

**Comment by patrickkenney9801** [comment]
Up to you I mean PP wold be good here as it would seem more business like but Prezi would be more interesting possibly getting of a better score but then again is not business like at all.

**Comment by firejake308** [comment]
Done
