### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by firejake308** [firejake308/code-versus-bugs#61]
Animate:
* Minions taking damage
* bomb tower explosions
* stunned malware

**Comment by patrickkenney9801** [comment]
ok fine make 3 animations for the high level malware that will be displayed
at 2/3 health and 1/3?

**Comment by firejake308** [comment]
Done with damage and stun animations

**Comment by firejake308** [comment]
The problem with the damage animation is that it makes the malware disintegrate, so extremely low-health viruses become nearly invisible. I plan to solve this with a small red dot or something at the center of each virus that will be behind the main sprite.

**Comment by firejake308** [comment]
Done! The current icon for all malware is a red circle with a white x
