### ISSUE TITLE
Bomb Tower Animations

### ISSUE THREAD

**Issue by firejake308** [firejake308/code-versus-bugs#66]
The bomb tower animation is really laggy and really lame. Can we do better?

**Comment by firejake308** [comment]
It is actually better than I thought it was. If we are satisfied with the status quo, we may close this issue.

**Comment by patrickkenney9801** [comment]
Everything I do, I do right. The first time. It is...logical.

**Comment by firejake308** [comment]
(whispers) It still doesn't look that great...
