### ISSUE TITLE
Hardware Tree

### ISSUE THREAD

**Issue by firejake308** [firejake308/code-versus-bugs#67]
A more interesting hardware tree would make a more interesting game. Therefore, we could implement some of the following changes:
- Switch buffer upgrade with Router upgrade to make defensive tree more enticing, since, at the moment, attack tree is OP.
- Find a more useful upgrade for support/utility tree than slow malware, which is undesirable, since the malware are slow enough as it is.
- Work in an upgrade on the green tree for more income from typing window
- Upgrade to increase efficiency of comm tower packages

**Comment by patrickkenney9801** [comment]
Not my area, I would help but it just is not my area.

**Comment by firejake308** [comment]
I am aware that I am in charge of the coding for this, but you have more
experience in video game balancing, so I just want to know if you think
these are good ideas.

**Comment by patrickkenney9801** [comment]
I do not know what either of those are, but it sounds good.
I agree with this.
Sounds logical, expand mini-game to make it an actual informational tool.
This might be a possibility but I am not sure, it sounds okay in theory.

**Comment by firejake308** [comment]
1. Buffer upgrade gives towers more health against worms.
2. But do you have any ideas?
3. Have you played through the new one in 1.6.0? It has 21 segments now instead of 11, and it teaches far more effectively.

**Comment by patrickkenney9801** [comment]
I do not know.

**Comment by patrickkenney9801** [comment]
Looks good from my perspective.
